package com.keeper.constants;

public class TestConstants {

    private TestConstants(){

    }

    public static final String URL = "http://localhost:";
    public static final String NOTE_TOO_LING_TITLE = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    //EXCEPTION CONSTANTS
    public static final String EXCEPTION_STATUS_KEY = "status";
    public static final String EXCEPTION_PATH_KEY = "path";
    public static final String EXCEPTION_MESSAGE_KEY = "message";

}
