server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keeper
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    platform: postgres
    show-sql: true
    hibernate:
      ddl-auto: update

cors:
  origin: http://localhost:4200
